name: Backfill preliminary NHSN HRD dataset
on:
  workflow_run:
    workflows: ["Fetch preliminary NHSN HRD dataset"]   # auto-trigger when preliminary data has been fetched succesfully
    types:
      - completed
  workflow_dispatch:  # allows manual trigger from Actions tab

permissions:
  contents: write         # Grants permission to push changes
  pull-requests: write    # Grants permission to create PRs

jobs:

  backfill_data:
    
    # Prevents automatic triggering after failed previous workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: BENTOLAB-HIERARCHSIR 
          environment-file: environment.lock.yml

      - name: Run backfill script
        shell: bash -l {0}
        run: |

          # needs the '-l {0}' flag to use the initialised conda environment

          python data/conversion/cases/backfill_preliminary-NHSN-HRD-data.py

      - name: Commit changes to a new feature branch
        shell: bash -l {0}
        run: |

          # generate timestamped branch name and store as environmental variable
          BRANCH_NAME="preliminary-data-backfill-$(date +'%Y%m%d%H%M%S')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          # configure git
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b "$BRANCH_NAME"
          
          # stage ONLY the data file
          git add -A
          git commit -m "NHSN HRD preliminary data backfilled on $(date +'%Y-%m-%d %H:%M:%S')"

          # Reset all other untracked changes just in case
          git reset --hard  
          git clean -fd    

          # push changes
          git push origin "$BRANCH_NAME"

      - name: Create a pull request
        shell: bash -l {0}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh pr create --base main --head ${{ env.BRANCH_NAME }} --title "Automated NHSN HRD Preliminary Data Backfill" --body "This PR includes the backfill of the preliminary NHSN HRD data."
      
      - name: Merge pull request
        shell: bash -l {0}
        run: |
          gh pr merge --delete-branch --squash

