name: Fetch preliminary NHSN HRD dataset

on:
# +---------------- minute (0 - 59)
# |  +------------- hour (0 - 23)
# |  |  +---------- day of month (1 - 31)
# |  |  |  +------- month (1 - 12)
# |  |  |  |  +---- day of week (0 - 6) (Sunday=0 or 7)
# |  |  |  |  |
# *  *  *  *  *  command to be executed
  schedule:
    - cron: '0 18 * 10-12 3' # Runs every Wednesday at 1:00 PM EDT (6:00 PM UTC) -- months 10-12
    - cron: '0 18 * 1-5 3' # Runs every Wednesday at 1:00 PM EDT (6:00 PM UTC) -- months 1-5
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write         # Grants permission to push changes
  pull-requests: write    # Grants permission to create PRs

jobs:
  pull_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: BENTOLAB-HIERARCHSIR 
          environment-file: BENTOLAB-HIERARCHSIR_conda-env.yml  
          auto-activate: false

      - name: Run data collection script
        shell: bash -l {0}
        run: |

          # needs the '-l {0}' flag to use the initialised conda environment

          python data/conversion/cases/fetch-format_NHSN-HRD-data.py --preliminary True

      - name: Commit changes to a new feature branch
        shell: bash -l {0}
        run: |

          # generate timestamped branch name and store as environmental variable
          BRANCH_NAME="preliminary-data-update-$(date +'%Y%m%d%H%M%S')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

          # configure git
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b "$BRANCH_NAME"
          
          # stage ONLY the data file
          git add -A
          git commit -m "NHSN HRD preliminary data update on $(date +'%Y-%m-%d %H:%M:%S')"

          # Reset all other untracked changes just in case
          git reset --hard  
          git clean -fd    

          # push changes
          git push origin "$BRANCH_NAME"

      - name: Create a pull request
        shell: bash -l {0}
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh pr create --base main --head ${{ env.BRANCH_NAME }} --title "Automated NHSN HRD Preliminary Data Update" --body "This PR includes the latest update of the preliminary NHSN HRD data."
      
      - name: Merge pull request
        shell: bash -l {0}
        run: |
          gh pr merge --delete-branch --squash

