name: Post results in Bento Lab Slack

on:
  workflow_call:          # As a child process of forecast_pipeline.yml
    secrets:
      SLACK_BOT_TOKEN:
        required: true
  workflow_dispatch:      # Allows manual triggering

jobs:

  post_results:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: BENTOLAB-HIERARCHSIR
          environment-file: BENTOLAB-HIERARCHSIR_conda-env.yml

      - name: Post in Bento Lab Slack channel 
        shell: bash -l {0}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          conda activate BENTOLAB-HIERARCHSIR
          python scripts/operational/slackbot.py