name: Post results in Bento Lab Slack
on:
  workflow_run:
    workflows: ["Visualise forecasts"]   # auto-trigger when preliminary data has been fetched succesfully
    types:
      - completed
  workflow_dispatch:  # allows manual trigger from Actions tab

jobs:

  post_results:

    # Prevents automatic triggering after failed previous workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: BENTOLAB-HIERARCHSIR
          environment-file: BENTOLAB-HIERARCHSIR_conda-env.yml

      - name: Post in Bento Lab Slack channel 
        shell: bash -l {0}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          conda activate BENTOLAB-HIERARCHSIR
          python scripts/operational/slackbot.py