name: Post results in Bento Lab Slack

on:
  workflow_call:          # As a child process of forecast_pipeline.yml
  workflow_dispatch:      # Allows manual triggering

jobs:

  post_results:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0 # (default: 1 ---> fetches only tip of main from the default origin at workflow start time ---> previous job added a new tip) 

      - name: Pull latest main
        shell: bash
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: BENTOLAB-HIERARCHSIR
          environment-file: BENTOLAB-HIERARCHSIR_conda-env.yml

      - name: Post in Bento Lab Slack channel 
        shell: bash -l {0}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        run: |
          conda activate BENTOLAB-HIERARCHSIR
          python scripts/operational/slackbot.py