name: Validate model setup

on: [pull_request]
jobs:
  validate_model_setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest',]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Install conda-lock
      run: 

    - name: Activate locked anaconda environment
      run: |
        conda install -c conda-forge conda-lock
        conda-lock install --name BENTOLAB-HIERARCHSIR --file conda-lock.yml --platform linux-64
        conda activate BENTOLAB-HIERARCHSIR

    - name: Install Boost Libraries
      shell: bash -l {0}
      run: |
        sudo apt-get update && sudo apt-get install -y libboost-all-dev

    - name: Install model code in BENTOLAB-HIERARCHSIR 
      shell: bash -l {0}
      run: |
        conda activate BENTOLAB-HIERARCHSIR
        python -m pip install --upgrade pip
        pip install -e . --force-reinstall