name: Validate model setup

on: [pull_request]
jobs:
  validate_model_setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest',]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.14'

    - name: Set up conda environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: BENTOLAB-HIERARCHSIR
        environment-file: BENTOLAB-HIERARCHSIR_conda-env.yml

    - name: Install Boost Libraries
      shell: bash -l {0}
      run: |
        conda activate BENTOLAB-HIERARCHSIR
        sudo apt-get update && sudo apt-get install -y libboost-all-dev

    - name: Install model code in BENTOLAB-HIERARCHSIR 
      shell: bash -l {0}
      run: |
        conda activate BENTOLAB-HIERARCHSIR
        python -m pip install --upgrade pip
        pip install -e . --force-reinstall